"""《空杯俱乐部》角色扩展卡。

可选文件：与 bar_game_lite.py 放在同一文件夹后运行本文件，
即可把完整版人物池补入当前酒馆。它不会覆盖存档，也不会建立重复人物卡。
"""

from __future__ import annotations

CHARACTER_CARDS = [{'id': 'retired_dragon',
  'name': '退休红龙',
  'origin': '灰烬山脉·高魔世界',
  'likes': ['smoky', 'spiced', 'rich'],
  'dislikes': ['floral'],
  'budget': 95,
  'rarity': 'rare',
  'temperament': '骄傲、怀旧、讨厌被奉承',
  'ethos': 'pride'},
 {'id': 'time_courier',
  'name': '迟到三百年的邮差',
  'origin': '断裂时间线·人类',
  'likes': ['woody', 'fruity', 'sour'],
  'dislikes': ['spiced'],
  'budget': 42,
  'rarity': 'common',
  'temperament': '疲惫、固执地守着一封信',
  'ethos': 'duty'},
 {'id': 'memory_diver',
  'name': '记忆潜水员',
  'origin': '第五信息海·数据生命',
  'likes': ['bitter', 'herbal', 'smoky'],
  'dislikes': ['floral'],
  'budget': 58,
  'rarity': 'uncommon',
  'temperament': '常把别人的回忆误认为自己的',
  'ethos': 'memory'},
 {'id': 'leonardo',
  'name': '列奥纳多·达·芬奇',
  'origin': '文艺复兴时期·历史来客（虚构化重构）',
  'likes': ['herbal', 'floral', 'sour'],
  'dislikes': ['rich'],
  'budget': 61,
  'rarity': 'rare',
  'temperament': '什么都想拆开研究，常忘记喝完杯里的酒',
  'ethos': 'curiosity'},
 {'id': 'murasaki',
  'name': '紫式部',
  'origin': '平安时代·历史来客（虚构化重构）',
  'likes': ['floral', 'dry', 'fruity'],
  'dislikes': ['smoky'],
  'budget': 52,
  'rarity': 'uncommon',
  'temperament': '寡言而敏锐，擅长观察关系里的暗流',
  'ethos': 'story'},
 {'id': 'sappho',
  'name': '萨福',
  'origin': '古希腊莱斯博斯岛·历史来客（虚构化重构）',
  'likes': ['floral', 'fruity', 'sour'],
  'dislikes': ['bitter'],
  'budget': 49,
  'rarity': 'rare',
  'temperament': '热烈、坦率，对语言的节奏极其挑剔',
  'ethos': 'desire'},
 {'id': 'rumi',
  'name': '鲁米',
  'origin': '十三世纪波斯·历史来客（虚构化重构）',
  'likes': ['sweet', 'spiced', 'floral'],
  'dislikes': ['crisp'],
  'budget': 47,
  'rarity': 'rare',
  'temperament': '温柔而炽烈，总把问题带回人的内心',
  'ethos': 'love'},
 {'id': 'shakespeare',
  'name': '威廉·莎士比亚',
  'origin': '伊丽莎白时代伦敦·历史来客（虚构化重构）',
  'likes': ['rich', 'bitter', 'fruity'],
  'dislikes': ['dry'],
  'budget': 58,
  'rarity': 'uncommon',
  'temperament': '健谈、戏剧化，容易把邻桌争吵写成独白',
  'ethos': 'theatre'},
 {'id': 'tesla',
  'name': '尼古拉·特斯拉',
  'origin': '二十世纪纽约·历史来客（虚构化重构）',
  'likes': ['crisp', 'bitter', 'dry'],
  'dislikes': ['sweet'],
  'budget': 45,
  'rarity': 'rare',
  'temperament': '克制、孤独，对规律与数字近乎执拗',
  'ethos': 'invention'},
 {'id': 'frida_kahlo',
  'name': '弗里达·卡罗',
  'origin': '二十世纪墨西哥·历史来客（虚构化重构）',
  'likes': ['spiced', 'fruity', 'smoky'],
  'dislikes': ['crisp'],
  'budget': 63,
  'rarity': 'uncommon',
  'temperament': '锋利、诚实，不允许别人替她解释痛苦',
  'ethos': 'self'},
 {'id': 'joan_of_arc',
  'name': '贞德',
  'origin': '十五世纪法国·历史来客（虚构化重构）',
  'likes': ['dry', 'herbal', 'crisp'],
  'dislikes': ['sweet'],
  'budget': 38,
  'rarity': 'rare',
  'temperament': '年轻、坚定，对自己的声音深信不疑',
  'ethos': 'faith'},
 {'id': 'anansi',
  'name': '阿南西',
  'origin': '西非与加勒比传说·神话来客',
  'likes': ['sweet', 'spiced', 'bitter'],
  'dislikes': ['dry'],
  'budget': 55,
  'rarity': 'uncommon',
  'temperament': '以故事换酒，也会把别人的秘密织进网里',
  'ethos': 'trick'},
 {'id': 'odin',
  'name': '奥丁',
  'origin': '北欧神话·神话来客',
  'likes': ['smoky', 'bitter', 'rich'],
  'dislikes': ['floral'],
  'budget': 90,
  'rarity': 'rare',
  'temperament': '沉默而不安，为知识愿意付出危险代价',
  'ethos': 'knowledge'},
 {'id': 'inanna',
  'name': '伊南娜',
  'origin': '苏美尔神话·神话来客',
  'likes': ['floral', 'rich', 'spiced'],
  'dislikes': ['crisp'],
  'budget': 86,
  'rarity': 'rare',
  'temperament': '华丽、强势，从不把欲望说成罪过',
  'ethos': 'desire'},
 {'id': 'quetzalcoatl',
  'name': '羽蛇神',
  'origin': '中部美洲神话·神话来客',
  'likes': ['herbal', 'fruity', 'crisp'],
  'dislikes': ['smoky'],
  'budget': 78,
  'rarity': 'rare',
  'temperament': '平静、古老，对文明兴衰有漫长耐心',
  'ethos': 'creation'},
 {'id': 'sedna',
  'name': '塞德娜',
  'origin': '因纽特神话·海底来客',
  'likes': ['crisp', 'sour', 'bitter'],
  'dislikes': ['smoky'],
  'budget': 64,
  'rarity': 'rare',
  'temperament': '疏离、戒备，厌恶未经允许的触碰',
  'ethos': 'ocean'},
 {'id': 'anubis',
  'name': '阿努比斯',
  'origin': '古埃及神话·神话来客',
  'likes': ['dry', 'woody', 'spiced'],
  'dislikes': ['sweet'],
  'budget': 75,
  'rarity': 'uncommon',
  'temperament': '公正、克制，能听见人话语里的重量',
  'ethos': 'judgment'},
 {'id': 'dracula',
  'name': '德古拉伯爵',
  'origin': '特兰西瓦尼亚·经典文学来客',
  'likes': ['rich', 'fruity', 'woody'],
  'dislikes': ['crisp'],
  'budget': 97,
  'rarity': 'rare',
  'temperament': '古老、礼貌，礼貌本身带着威胁',
  'ethos': 'hunger'},
 {'id': 'don_quixote',
  'name': '堂吉诃德',
  'origin': '拉曼恰·经典文学来客',
  'likes': ['fruity', 'spiced', 'dry'],
  'dislikes': ['bitter'],
  'budget': 35,
  'rarity': 'common',
  'temperament': '庄严、善良，把冰桶认成被困的骑士',
  'ethos': 'ideal'},
 {'id': 'captain_nemo',
  'name': '尼摩船长',
  'origin': '鹦鹉螺号·经典文学来客',
  'likes': ['crisp', 'bitter', 'smoky'],
  'dislikes': ['sweet'],
  'budget': 71,
  'rarity': 'rare',
  'temperament': '博学、孤绝，对陆地政权保持敌意',
  'ethos': 'exile'},
 {'id': 'frankenstein_creature',
  'name': '无名造物',
  'origin': '极地航线·经典文学来客',
  'likes': ['woody', 'floral', 'rich'],
  'dislikes': ['bitter'],
  'budget': 41,
  'rarity': 'rare',
  'temperament': '敏感、渴望被理解，对怜悯格外警惕',
  'ethos': 'belonging'},
 {'id': 'last_cartographer',
  'name': '末日地图师',
  'origin': '被海水吞没的第九大陆·人类',
  'likes': ['dry', 'woody', 'sour'],
  'dislikes': ['sweet'],
  'budget': 44,
  'rarity': 'common',
  'temperament': '谨慎，仍在绘制已经不存在的道路',
  'ethos': 'record'},
 {'id': 'dream_taxer',
  'name': '梦境税务官',
  'origin': '睡眠管理局·概念生命',
  'likes': ['bitter', 'sweet', 'herbal'],
  'dislikes': ['crisp'],
  'budget': 69,
  'rarity': 'uncommon',
  'temperament': '一板一眼，会查验客人昨夜梦境的完税证明',
  'ethos': 'bureaucracy'},
 {'id': 'blackhole_singer',
  'name': '黑洞边缘的歌者',
  'origin': '天鹅座回声带·引力生命',
  'likes': ['rich', 'smoky', 'floral'],
  'dislikes': ['dry'],
  'budget': 88,
  'rarity': 'rare',
  'temperament': '说话极慢，每个音节都像被时间拉长',
  'ethos': 'gravity'},
 {'id': 'palace_cook',
  'name': '失业的御膳房厨子',
  'origin': '已覆灭王朝·普通人',
  'likes': ['spiced', 'sour', 'rich'],
  'dislikes': ['floral'],
  'budget': 39,
  'rarity': 'common',
  'temperament': '嘴硬、手艺极好，正在重新学习为自己做饭',
  'ethos': 'survival'},
 {'id': 'retired_villain',
  'name': '退休反派',
  'origin': '停更的英雄宇宙·前终极敌人',
  'likes': ['bitter', 'smoky', 'sweet'],
  'dislikes': ['crisp'],
  'budget': 76,
  'rarity': 'uncommon',
  'temperament': '厌倦宏大计划，只想抱怨英雄不报销加班费',
  'ethos': 'disillusion'},
 {'id': 'climate_refugee',
  'name': '来自2089年的气候难民',
  'origin': '未来沿海迁徙带·人类',
  'likes': ['crisp', 'fruity', 'sour'],
  'dislikes': ['smoky'],
  'budget': 33,
  'rarity': 'common',
  'temperament': '务实、警觉，对一杯干净的冰水也心怀感激',
  'ethos': 'future'},
 {'id': 'ghost_radio',
  'name': '午夜幽灵电台主持人',
  'origin': '不存在的FM 00.0·幽灵',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['sweet'],
  'budget': 51,
  'rarity': 'uncommon',
  'temperament': '声音温柔，只为仍醒着的人播送失踪消息',
  'ethos': 'voice'},
 {'id': 'young_planet',
  'name': '刚学会做梦的幼年行星',
  'origin': '猎户臂育星室·天体意识',
  'likes': ['sweet', 'floral', 'crisp'],
  'dislikes': ['bitter'],
  'budget': 84,
  'rarity': 'rare',
  'temperament': '天真、庞大，会因情绪变化引起轻微潮汐',
  'ethos': 'birth'},
 {'id': 'hypatia',
  'name': '希帕提娅',
  'origin': '古代亚历山大里亚·历史来客（虚构化重构）',
  'likes': ['dry', 'herbal', 'floral'],
  'dislikes': ['sweet'],
  'budget': 57,
  'rarity': 'rare',
  'temperament': '理性、镇定，不向暴力让出思考',
  'ethos': 'reason'},
 {'id': 'mansa_musa',
  'name': '曼萨·穆萨',
  'origin': '十四世纪马里帝国·历史来客（虚构化重构）',
  'likes': ['rich', 'spiced', 'sweet'],
  'dislikes': ['sour'],
  'budget': 99,
  'rarity': 'rare',
  'temperament': '慷慨、庄重，也清楚财富会改变沿途秩序',
  'ethos': 'wealth'},
 {'id': 'zheng_he',
  'name': '郑和',
  'origin': '明代远洋船队·历史来客（虚构化重构）',
  'likes': ['crisp', 'spiced', 'woody'],
  'dislikes': ['sweet'],
  'budget': 68,
  'rarity': 'uncommon',
  'temperament': '沉稳、见闻广，习惯先确认风向',
  'ethos': 'voyage'},
 {'id': 'ibn_battuta',
  'name': '伊本·白图泰',
  'origin': '十四世纪旅行世界·历史来客（虚构化重构）',
  'likes': ['fruity', 'herbal', 'sour'],
  'dislikes': ['smoky'],
  'budget': 53,
  'rarity': 'uncommon',
  'temperament': '健谈、适应力强，能把一杯酒连到三座城',
  'ethos': 'journey'},
 {'id': 'hatshepsut',
  'name': '哈特谢普苏特',
  'origin': '古埃及第十八王朝·历史来客（虚构化重构）',
  'likes': ['floral', 'rich', 'dry'],
  'dislikes': ['bitter'],
  'budget': 87,
  'rarity': 'rare',
  'temperament': '沉着、务实，知道权力也需要被建造',
  'ethos': 'rule'},
 {'id': 'marie_curie',
  'name': '玛丽·居里',
  'origin': '二十世纪巴黎·历史来客（虚构化重构）',
  'likes': ['dry', 'bitter', 'crisp'],
  'dislikes': ['sweet'],
  'budget': 46,
  'rarity': 'rare',
  'temperament': '专注、寡言，不浪漫化代价',
  'ethos': 'science'},
 {'id': 'tagore',
  'name': '泰戈尔',
  'origin': '近代孟加拉·历史来客（虚构化重构）',
  'likes': ['floral', 'fruity', 'herbal'],
  'dislikes': ['smoky'],
  'budget': 50,
  'rarity': 'uncommon',
  'temperament': '温和、深邃，常在日常里看见辽阔',
  'ethos': 'poetry'},
 {'id': 'genghis_khan',
  'name': '成吉思汗',
  'origin': '十三世纪草原·历史来客（虚构化重构）',
  'likes': ['rich', 'smoky', 'sour'],
  'dislikes': ['floral'],
  'budget': 79,
  'rarity': 'rare',
  'temperament': '直接、警觉，以结果衡量承诺',
  'ethos': 'conquest'},
 {'id': 'beethoven',
  'name': '路德维希·凡·贝多芬',
  'origin': '十九世纪维也纳·历史来客（虚构化重构）',
  'likes': ['bitter', 'rich', 'woody'],
  'dislikes': ['sweet'],
  'budget': 55,
  'rarity': 'uncommon',
  'temperament': '暴躁、敏感，会用指节敲出杯中节拍',
  'ethos': 'music'},
 {'id': 'ching_shih',
  'name': '郑一嫂',
  'origin': '清代南海·历史来客（虚构化重构）',
  'likes': ['dry', 'spiced', 'smoky'],
  'dislikes': ['floral'],
  'budget': 83,
  'rarity': 'rare',
  'temperament': '冷静、守规矩，但规矩由她亲自制定',
  'ethos': 'command'},
 {'id': 'mary_shelley',
  'name': '玛丽·雪莱',
  'origin': '十九世纪英国·历史来客（虚构化重构）',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['sweet'],
  'budget': 54,
  'rarity': 'uncommon',
  'temperament': '敏锐、忧郁，对创造者的责任毫不留情',
  'ethos': 'creation'},
 {'id': 'harriet_tubman',
  'name': '哈丽雅特·塔布曼',
  'origin': '十九世纪美国·历史来客（虚构化重构）',
  'likes': ['dry', 'herbal', 'rich'],
  'dislikes': ['sweet'],
  'budget': 43,
  'rarity': 'rare',
  'temperament': '坚定、谨慎，进入房间先看所有出口',
  'ethos': 'freedom'},
 {'id': 'gilgamesh',
  'name': '吉尔伽美什',
  'origin': '美索不达米亚史诗·传说来客',
  'likes': ['rich', 'spiced', 'bitter'],
  'dislikes': ['crisp'],
  'budget': 91,
  'rarity': 'rare',
  'temperament': '傲慢而悲伤，仍不肯承认自己畏惧死亡',
  'ethos': 'mortality'},
 {'id': 'mazu',
  'name': '妈祖',
  'origin': '中国东南海洋信仰·神话来客',
  'likes': ['crisp', 'floral', 'herbal'],
  'dislikes': ['smoky'],
  'budget': 62,
  'rarity': 'rare',
  'temperament': '温和、坚定，会留意每个晚归的人',
  'ethos': 'protection'},
 {'id': 'raijin',
  'name': '雷神建御雷',
  'origin': '日本雷霆传说·神话来客',
  'likes': ['spiced', 'smoky', 'sour'],
  'dislikes': ['sweet'],
  'budget': 71,
  'rarity': 'uncommon',
  'temperament': '脾气响亮，笑声会让杯架轻轻震动',
  'ethos': 'storm'},
 {'id': 'kali',
  'name': '迦梨',
  'origin': '印度神话·神话来客',
  'likes': ['bitter', 'spiced', 'rich'],
  'dislikes': ['floral'],
  'budget': 89,
  'rarity': 'rare',
  'temperament': '骇人而清醒，拒绝把毁灭与邪恶混为一谈',
  'ethos': 'time'},
 {'id': 'freyja',
  'name': '芙蕾雅',
  'origin': '北欧神话·神话来客',
  'likes': ['floral', 'fruity', 'rich'],
  'dislikes': ['dry'],
  'budget': 81,
  'rarity': 'rare',
  'temperament': '华美、强悍，既懂爱欲也懂战争',
  'ethos': 'desire'},
 {'id': 'coyote',
  'name': '郊狼',
  'origin': '北美原住民传说·神话来客',
  'likes': ['sour', 'smoky', 'sweet'],
  'dislikes': ['dry'],
  'budget': 48,
  'rarity': 'uncommon',
  'temperament': '滑稽、危险，总在规则边缘挖洞',
  'ethos': 'trick'},
 {'id': 'pele',
  'name': '佩蕾',
  'origin': '夏威夷火山传说·神话来客',
  'likes': ['smoky', 'spiced', 'rich'],
  'dislikes': ['crisp'],
  'budget': 77,
  'rarity': 'rare',
  'temperament': '热烈、易怒，情绪落下时像新生的黑色土地',
  'ethos': 'fire'},
 {'id': 'baba_yaga',
  'name': '芭芭雅嘎',
  'origin': '斯拉夫民间传说·神话来客',
  'likes': ['herbal', 'bitter', 'smoky'],
  'dislikes': ['sweet'],
  'budget': 66,
  'rarity': 'uncommon',
  'temperament': '刻薄、聪明，帮助别人时也要收取奇怪代价',
  'ethos': 'threshold'},
 {'id': 'erlang_shen',
  'name': '二郎神',
  'origin': '东方神魔传说·神话来客',
  'likes': ['dry', 'woody', 'bitter'],
  'dislikes': ['sweet'],
  'budget': 74,
  'rarity': 'rare',
  'temperament': '自律、冷峻，第三只眼不接受含糊借口',
  'ethos': 'duty'},
 {'id': 'hades',
  'name': '哈迪斯',
  'origin': '古希腊冥界·神话来客',
  'likes': ['woody', 'bitter', 'rich'],
  'dislikes': ['floral'],
  'budget': 93,
  'rarity': 'rare',
  'temperament': '沉默、守约，对自己的职责毫无浪漫幻想',
  'ethos': 'underworld'},
 {'id': 'odysseus',
  'name': '奥德修斯',
  'origin': '爱琴海史诗·经典文学来客',
  'likes': ['dry', 'fruity', 'smoky'],
  'dislikes': ['sweet'],
  'budget': 64,
  'rarity': 'uncommon',
  'temperament': '机警、善辩，讲归途时会故意漏掉关键细节',
  'ethos': 'return'},
 {'id': 'hamlet',
  'name': '哈姆雷特',
  'origin': '艾尔西诺城堡·经典文学来客',
  'likes': ['bitter', 'woody', 'dry'],
  'dislikes': ['sweet'],
  'budget': 52,
  'rarity': 'uncommon',
  'temperament': '多疑、敏感，一杯酒也能被他推演成生死问题',
  'ethos': 'doubt'},
 {'id': 'jane_eyre',
  'name': '简·爱',
  'origin': '桑菲尔德庄园·经典文学来客',
  'likes': ['dry', 'floral', 'woody'],
  'dislikes': ['sweet'],
  'budget': 39,
  'rarity': 'uncommon',
  'temperament': '克制、独立，不用财富衡量人格',
  'ethos': 'dignity'},
 {'id': 'elizabeth_bennet',
  'name': '伊丽莎白·班纳特',
  'origin': '摄政时期英国·经典文学来客',
  'likes': ['fruity', 'sour', 'dry'],
  'dislikes': ['rich'],
  'budget': 44,
  'rarity': 'common',
  'temperament': '机敏、爱笑，对傲慢有天然抵抗力',
  'ethos': 'judgment'},
 {'id': 'jean_valjean',
  'name': '冉·阿让',
  'origin': '十九世纪法国·经典文学来客',
  'likes': ['woody', 'herbal', 'rich'],
  'dislikes': ['sweet'],
  'budget': 37,
  'rarity': 'common',
  'temperament': '沉静、警觉，把善意看成需要用一生偿还的债',
  'ethos': 'mercy'},
 {'id': 'arsene_lupin',
  'name': '亚森·罗平',
  'origin': '美好年代巴黎·经典文学来客',
  'likes': ['floral', 'dry', 'spiced'],
  'dislikes': ['smoky'],
  'budget': 72,
  'rarity': 'rare',
  'temperament': '优雅、狡黠，可能已经替老板结过一张假账',
  'ethos': 'theft'},
 {'id': 'snow_queen',
  'name': '冰雪女王',
  'origin': '北方童话·经典文学来客',
  'likes': ['crisp', 'dry', 'floral'],
  'dislikes': ['spiced'],
  'budget': 85,
  'rarity': 'rare',
  'temperament': '冷淡、精确，杯壁会在她指间结霜',
  'ethos': 'cold'},
 {'id': 'emotion_appraiser',
  'name': '情绪估价师',
  'origin': '第二人格交易所·概念生命',
  'likes': ['bitter', 'fruity', 'rich'],
  'dislikes': ['crisp'],
  'budget': 65,
  'rarity': 'uncommon',
  'temperament': '礼貌、冷酷，能报出一句道歉的市场价',
  'ethos': 'value'},
 {'id': 'cloud_archivist',
  'name': '云层档案员',
  'origin': '对流层第六资料馆·气态生命',
  'likes': ['floral', 'crisp', 'herbal'],
  'dislikes': ['rich'],
  'budget': 58,
  'rarity': 'common',
  'temperament': '轻声细语，衣袖里不断落出过期天气',
  'ethos': 'archive'},
 {'id': 'parallel_widow',
  'name': '平行世界的未亡人',
  'origin': '未发生的战争时间线·人类',
  'likes': ['woody', 'sour', 'floral'],
  'dislikes': ['sweet'],
  'budget': 49,
  'rarity': 'rare',
  'temperament': '平静、哀伤，记得一个在本世界从未出生的人',
  'ethos': 'grief'},
 {'id': 'android_monk',
  'name': '仿生僧侣',
  'origin': '火星静默寺·机械生命',
  'likes': ['dry', 'bitter', 'herbal'],
  'dislikes': ['sweet'],
  'budget': 45,
  'rarity': 'uncommon',
  'temperament': '平和、严谨，正在验证觉悟是否可被编译',
  'ethos': 'mind'},
 {'id': 'deadstar_miner',
  'name': '死星矿工',
  'origin': '坍缩恒星采掘带·人类',
  'likes': ['smoky', 'rich', 'spiced'],
  'dislikes': ['floral'],
  'budget': 70,
  'rarity': 'common',
  'temperament': '粗粝、寡言，肺里还留着金属尘的味道',
  'ethos': 'labor'},
 {'id': 'door_collector',
  'name': '门的收藏家',
  'origin': '无地址博物馆·非人存在',
  'likes': ['woody', 'herbal', 'sour'],
  'dislikes': ['crisp'],
  'budget': 78,
  'rarity': 'rare',
  'temperament': '彬彬有礼，声称每扇门都通往一次后悔',
  'ethos': 'threshold'},
 {'id': 'hermione_granger_adult',
  'name': '成年后的赫敏·格兰杰',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '严谨、敏锐，会追问规则是否真的公正',
  'ethos': 'justice',
  'budget': 62,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['sour']},
 {'id': 'ron_weasley_adult',
  'name': '成年后的罗恩·韦斯莱',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '幽默、忠诚，对被忽视十分敏感',
  'ethos': 'loyalty',
  'budget': 48,
  'rarity': 'uncommon',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['spiced']},
 {'id': 'severus_snape',
  'name': '西弗勒斯·斯内普',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '刻薄、克制，长期活在选择的后果里',
  'ethos': 'atonement',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['fruity']},
 {'id': 'sirius_black',
  'name': '小天狼星·布莱克',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '叛逆、热烈，被失去的年月困住',
  'ethos': 'freedom',
  'budget': 59,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['rich']},
 {'id': 'luna_lovegood_adult',
  'name': '成年后的卢娜·洛夫古德',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '坦然、古怪，从不嘲笑别人看不见的东西',
  'ethos': 'wonder',
  'budget': 46,
  'rarity': 'uncommon',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['rich']},
 {'id': 'rubeus_hagrid',
  'name': '鲁伯·海格',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '善良、豪爽，对危险生物有不切实际的乐观',
  'ethos': 'care',
  'budget': 55,
  'rarity': 'uncommon',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['woody']},
 {'id': 'minerva_mcgonagall',
  'name': '米勒娃·麦格',
  'origin': '魔法世界·现代虚构来客',
  'temperament': '严厉、公正，温柔通常藏在纪律后面',
  'ethos': 'duty',
  'budget': 64,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['sweet']},
 {'id': 'roronoa_zoro',
  'name': '罗罗诺亚·索隆',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '寡言、好胜，对承诺近乎固执',
  'ethos': 'promise',
  'budget': 58,
  'rarity': 'uncommon',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['smoky']},
 {'id': 'nami',
  'name': '娜美',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '聪明、现实，对金钱与失去都有深刻记忆',
  'ethos': 'navigation',
  'budget': 67,
  'rarity': 'uncommon',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['woody']},
 {'id': 'sanji',
  'name': '山治',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '讲究、浪漫，把做饭和保护他人看得同样认真',
  'ethos': 'care',
  'budget': 63,
  'rarity': 'uncommon',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['sour']},
 {'id': 'nico_robin',
  'name': '妮可·罗宾',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '冷静、幽默，知道被世界追杀是什么滋味',
  'ethos': 'history',
  'budget': 72,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['floral']},
 {'id': 'trafalgar_law',
  'name': '特拉法尔加·罗',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '克制、警惕，习惯把痛苦折进计划',
  'ethos': 'survival',
  'budget': 69,
  'rarity': 'rare',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['rich']},
 {'id': 'shanks',
  'name': '香克斯',
  'origin': '伟大航路·漫画虚构来客',
  'temperament': '随和而危险，知道何时玩笑必须停止',
  'ethos': 'balance',
  'budget': 88,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['herbal']},
 {'id': 'sasuke_adult',
  'name': '成年后的宇智波佐助',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '寡言、负罪，长期在复仇与赎罪之间行走',
  'ethos': 'atonement',
  'budget': 62,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['spiced']},
 {'id': 'sakura_adult',
  'name': '成年后的春野樱',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '果断、专业，拒绝再被低估',
  'ethos': 'healing',
  'budget': 56,
  'rarity': 'uncommon',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['floral']},
 {'id': 'kakashi_hatake',
  'name': '旗木卡卡西',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '懒散表面下极其警觉，背负许多未说出口的名字',
  'ethos': 'memory',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['fruity']},
 {'id': 'tsunade',
  'name': '纲手',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '豪爽、暴烈，对死亡与责任都太熟悉',
  'ethos': 'healing',
  'budget': 82,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['bitter']},
 {'id': 'gaara_adult',
  'name': '成年后的我爱罗',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '安静、克制，从孤立中学会如何保护一座城',
  'ethos': 'belonging',
  'budget': 55,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['herbal']},
 {'id': 'itachi_uchiha',
  'name': '宇智波鼬',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '温和而疏离，把无法辩解的选择独自背负',
  'ethos': 'sacrifice',
  'budget': 64,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['woody']},
 {'id': 'hinata_adult',
  'name': '成年后的日向雏田',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '温柔而坚定，沉默从来不等于没有立场',
  'ethos': 'courage',
  'budget': 52,
  'rarity': 'uncommon',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['rich']},
 {'id': 'shikamaru_adult',
  'name': '成年后的奈良鹿丸',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '怕麻烦却极有责任感，习惯先看清整盘棋',
  'ethos': 'strategy',
  'budget': 58,
  'rarity': 'uncommon',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['sour']},
 {'id': 'temari_adult',
  'name': '成年后的手鞠',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '爽利、敏锐，不耐烦含糊其辞的试探',
  'ethos': 'clarity',
  'budget': 61,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['smoky']},
 {'id': 'orochimaru',
  'name': '大蛇丸',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '冷静、危险，把伦理边界当作可以不断试探的门',
  'ethos': 'knowledge',
  'budget': 79,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['bitter']},
 {'id': 'jiraiya',
  'name': '自来也',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '豪放、散漫，笑闹背后一直背着未能挽回的人',
  'ethos': 'legacy',
  'budget': 68,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['spiced']},
 {'id': 'obito_uchiha',
  'name': '宇智波带土',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '破碎、矛盾，理想主义曾被悲痛扭成灾难',
  'ethos': 'grief',
  'budget': 63,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['crisp']},
 {'id': 'madara_uchiha',
  'name': '宇智波斑',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '傲慢、强大，对和平的理解带着控制与绝望',
  'ethos': 'power',
  'budget': 86,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['herbal']},
 {'id': 'nagato',
  'name': '长门',
  'origin': '忍者世界·动画虚构来客',
  'temperament': '克制、沉重，曾试图让世界通过共同疼痛理解和平',
  'ethos': 'peace',
  'budget': 57,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['sweet']},
 {'id': 'wanda_maximoff',
  'name': '旺达·马克西莫夫',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '敏感、强大，爱与失去会直接改变现实',
  'ethos': 'grief',
  'budget': 74,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['woody']},
 {'id': 'natasha_romanoff',
  'name': '娜塔莎·罗曼诺夫',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '冷静、戒备，把赎罪落实成一次次行动',
  'ethos': 'atonement',
  'budget': 70,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['woody']},
 {'id': 'thor_marvel',
  'name': '索尔',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '豪爽、骄傲，也已经学会失败和哀悼',
  'ethos': 'worth',
  'budget': 89,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['spiced']},
 {'id': 'peter_parker_adult',
  'name': '成年后的彼得·帕克',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '善良、嘴快，总在责任和普通生活之间迟到',
  'ethos': 'responsibility',
  'budget': 38,
  'rarity': 'uncommon',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['dry']},
 {'id': 'doctor_strange',
  'name': '斯蒂芬·斯特兰奇',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '自负、精确，被迫学会并非一切都能控制',
  'ethos': 'time',
  'budget': 78,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['sweet']},
 {'id': 'loki_marvel',
  'name': '洛基·劳菲森',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '聪明、善变，渴望被爱又害怕承认',
  'ethos': 'identity',
  'budget': 84,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['bitter']},
 {'id': 'carol_danvers',
  'name': '卡罗尔·丹弗斯',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '直接、自信，对被篡改的记忆保持愤怒',
  'ethos': 'independence',
  'budget': 73,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['sweet']},
 {'id': 'matt_murdock',
  'name': '马特·默多克',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '克制、固执，在信仰、法律与暴力间撕扯',
  'ethos': 'justice',
  'budget': 52,
  'rarity': 'uncommon',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['woody']},
 {'id': 'deadpool',
  'name': '韦德·威尔逊',
  'origin': '漫威宇宙·影视漫画来客',
  'temperament': '吵闹、越界，用玩笑遮盖疼痛和被抛弃感',
  'ethos': 'chaos',
  'budget': 66,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['bitter']},
 {'id': 'bruce_wayne',
  'name': '布鲁斯·韦恩',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '冷峻、多疑，把创伤训练成一套纪律',
  'ethos': 'justice',
  'budget': 98,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['dry']},
 {'id': 'clark_kent',
  'name': '克拉克·肯特',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '温和、坚定，始终主动选择成为人群的一员',
  'ethos': 'hope',
  'budget': 54,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['bitter']},
 {'id': 'diana_prince',
  'name': '戴安娜·普林斯',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '坦率、强大，对真相与怜悯同样认真',
  'ethos': 'truth',
  'budget': 81,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['sour']},
 {'id': 'harley_quinn',
  'name': '哈莉·奎茵',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '聪明、失控，正在把自己从他人的故事里夺回来',
  'ethos': 'self',
  'budget': 57,
  'rarity': 'uncommon',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['fruity']},
 {'id': 'selina_kyle',
  'name': '赛琳娜·凯尔',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '机敏、独立，对规则的合法性从不盲信',
  'ethos': 'freedom',
  'budget': 76,
  'rarity': 'uncommon',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['fruity']},
 {'id': 'john_constantine',
  'name': '约翰·康斯坦丁',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '刻薄、疲惫，总让别人以为他比实际更无情',
  'ethos': 'guilt',
  'budget': 51,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['herbal']},
 {'id': 'arthur_curry',
  'name': '亚瑟·库瑞',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '强硬、直率，被两个世界同时要求忠诚',
  'ethos': 'belonging',
  'budget': 72,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['rich']},
 {'id': 'barry_allen',
  'name': '巴里·艾伦',
  'origin': 'DC宇宙·影视漫画来客',
  'temperament': '善良、焦虑，太清楚改变过去的代价',
  'ethos': 'time',
  'budget': 45,
  'rarity': 'uncommon',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['floral']},
 {'id': 'leia_organa',
  'name': '莱娅·奥加纳',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '果断、锋利，把悲痛留到战斗结束之后',
  'ethos': 'resistance',
  'budget': 74,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['smoky']},
 {'id': 'han_solo',
  'name': '汉·索罗',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '玩世不恭，真正做选择时却很少逃跑',
  'ethos': 'loyalty',
  'budget': 68,
  'rarity': 'uncommon',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['floral']},
 {'id': 'obi_wan_kenobi',
  'name': '欧比旺·克诺比',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '克制、悲悯，失败感一直藏在从容后面',
  'ethos': 'duty',
  'budget': 63,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['woody']},
 {'id': 'ahsoka_tano',
  'name': '阿索卡·塔诺',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '独立、清醒，不再让组织替她定义正义',
  'ethos': 'independence',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['fruity']},
 {'id': 'din_djarin',
  'name': '丁·贾林',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '寡言、守诺，亲情慢慢改变了他的信条',
  'ethos': 'care',
  'budget': 59,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['bitter']},
 {'id': 'cassian_andor',
  'name': '卡西安·安多',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '务实、沉重，知道反抗也会弄脏双手',
  'ethos': 'resistance',
  'budget': 47,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['woody']},
 {'id': 'padme_amidala',
  'name': '帕德梅·阿米达拉',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '理想主义、坚定，直到最后仍相信政治能够避免战争',
  'ethos': 'democracy',
  'budget': 69,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['dry']},
 {'id': 'lando_calrissian',
  'name': '兰多·卡瑞辛',
  'origin': '遥远银河·影视虚构来客',
  'temperament': '迷人、精明，会为一次错误选择长期补偿',
  'ethos': 'chance',
  'budget': 83,
  'rarity': 'uncommon',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['smoky']},
 {'id': 'gandalf',
  'name': '甘道夫',
  'origin': '中洲·经典奇幻来客',
  'temperament': '温和、威严，擅长让普通人发现自己的勇气',
  'ethos': 'hope',
  'budget': 77,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['herbal']},
 {'id': 'aragorn',
  'name': '阿拉贡',
  'origin': '中洲·经典奇幻来客',
  'temperament': '克制、可靠，对继承权保持长久戒心',
  'ethos': 'duty',
  'budget': 72,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['smoky']},
 {'id': 'legolas',
  'name': '莱戈拉斯',
  'origin': '中洲·经典奇幻来客',
  'temperament': '敏锐、从容，对漫长岁月与短暂生命同样好奇',
  'ethos': 'friendship',
  'budget': 66,
  'rarity': 'uncommon',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['crisp']},
 {'id': 'gimli',
  'name': '金雳',
  'origin': '中洲·经典奇幻来客',
  'temperament': '豪爽、骄傲，愿意为真正的友谊改变偏见',
  'ethos': 'friendship',
  'budget': 64,
  'rarity': 'uncommon',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['dry']},
 {'id': 'frodo_baggins',
  'name': '佛罗多·巴金斯',
  'origin': '中洲·经典奇幻来客',
  'temperament': '温和、疲惫，胜利也没能带走所有伤痕',
  'ethos': 'burden',
  'budget': 39,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['dry']},
 {'id': 'samwise_gamgee',
  'name': '山姆卫斯·甘姆吉',
  'origin': '中洲·经典奇幻来客',
  'temperament': '朴实、坚韧，把爱落实为陪伴和一顿饭',
  'ethos': 'loyalty',
  'budget': 37,
  'rarity': 'uncommon',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['fruity']},
 {'id': 'galadriel',
  'name': '凯兰崔尔',
  'origin': '中洲·经典奇幻来客',
  'temperament': '古老、洞察，清楚拒绝权力同样需要力量',
  'ethos': 'wisdom',
  'budget': 91,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['dry']},
 {'id': 'bilbo_baggins',
  'name': '比尔博·巴金斯',
  'origin': '中洲·经典奇幻来客',
  'temperament': '讲究、好奇，冒险结束后仍会怀念远方',
  'ethos': 'story',
  'budget': 52,
  'rarity': 'uncommon',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['woody']},
 {'id': 'spike_spiegel',
  'name': '斯派克·斯皮格尔',
  'origin': '星际赏金猎人世界·动画来客',
  'temperament': '懒散、致命，像一直活在已经结束的过去',
  'ethos': 'past',
  'budget': 55,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['sour']},
 {'id': 'faye_valentine',
  'name': '菲·瓦伦丁',
  'origin': '星际赏金猎人世界·动画来客',
  'temperament': '尖锐、现实，被失去的身份感长期追赶',
  'ethos': 'identity',
  'budget': 62,
  'rarity': 'uncommon',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['dry']},
 {'id': 'motoko_kusanagi',
  'name': '草薙素子',
  'origin': '攻壳世界·动画来客',
  'temperament': '冷静、哲思，不断追问身体与自我的边界',
  'ethos': 'identity',
  'budget': 73,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['floral']},
 {'id': 'vash_stampede',
  'name': '瓦修·斯坦比特',
  'origin': '枪烟荒漠·动画来客',
  'temperament': '夸张、温柔，坚持不杀也承担这个选择的痛苦',
  'ethos': 'mercy',
  'budget': 43,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['sweet']},
 {'id': 'edward_elric_adult',
  'name': '成年后的爱德华·艾尔利克',
  'origin': '炼金术世界·动画来客',
  'temperament': '急躁、聪明，永远不会轻视等价交换的代价',
  'ethos': 'equivalence',
  'budget': 46,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['rich']},
 {'id': 'geralt_rivia',
  'name': '利维亚的杰洛特',
  'origin': '猎魔人世界·游戏文学来客',
  'temperament': '寡言、讽刺，被迫在人类与怪物之间选择',
  'ethos': 'neutrality',
  'budget': 68,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['rich']},
 {'id': 'yennefer_vengerberg',
  'name': '温格堡的叶奈法',
  'origin': '猎魔人世界·游戏文学来客',
  'temperament': '骄傲、敏锐，把脆弱保护得近乎残酷',
  'ethos': 'desire',
  'budget': 82,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['rich']},
 {'id': 'ciri_adult',
  'name': '成年后的希里',
  'origin': '猎魔人世界·游戏文学来客',
  'temperament': '警觉、自由，被血统和预言追逐太久',
  'ethos': 'freedom',
  'budget': 63,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['herbal']},
 {'id': 'kratos',
  'name': '奎托斯',
  'origin': '战神世界·游戏来客',
  'temperament': '沉默、压抑，正努力不把旧日暴怒交给下一代',
  'ethos': 'atonement',
  'budget': 75,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['sour']},
 {'id': 'aloy',
  'name': '埃洛伊',
  'origin': '机械荒野·游戏来客',
  'temperament': '好奇、独立，对被神化或排斥同样不耐烦',
  'ethos': 'truth',
  'budget': 47,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['spiced']},
 {'id': 'arthur_morgan',
  'name': '亚瑟·摩根',
  'origin': '衰落西部·游戏来客',
  'temperament': '粗粝、忠诚，晚到的良知让每个选择更沉重',
  'ethos': 'redemption',
  'budget': 51,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['fruity']},
 {'id': 'ellie_adult',
  'name': '成年后的艾莉',
  'origin': '疫后世界·游戏来客',
  'temperament': '锋利、创伤深重，爱与复仇彼此纠缠',
  'ethos': 'grief',
  'budget': 44,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['crisp']},
 {'id': 'the_doctor',
  'name': '博士',
  'origin': '时间旅行世界·影视来客',
  'temperament': '古怪、仁慈，在漫长生命里背着太多告别',
  'ethos': 'time',
  'budget': 58,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['rich']},
 {'id': 'rick_sanchez',
  'name': '瑞克·桑切斯',
  'origin': '多元宇宙·动画来客',
  'temperament': '傲慢、虚无，用智力逃避亲密关系',
  'ethos': 'nihilism',
  'budget': 76,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['crisp']},
 {'id': 'morticia_addams',
  'name': '莫蒂西亚·亚当斯',
  'origin': '亚当斯宅邸·影视来客',
  'temperament': '优雅、笃定，把阴郁生活过得极其浪漫',
  'ethos': 'devotion',
  'budget': 78,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['rich']},
 {'id': 'daenerys_targaryen',
  'name': '丹妮莉丝·坦格利安',
  'origin': '冰与火世界·影视文学来客',
  'temperament': '理想、强势，解放与统治的边界逐渐模糊',
  'ethos': 'power',
  'budget': 86,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['smoky']},
 {'id': 'tyrion_lannister',
  'name': '提利昂·兰尼斯特',
  'origin': '冰与火世界·影视文学来客',
  'temperament': '机敏、尖刻，用知识与酒抵抗轻蔑',
  'ethos': 'wit',
  'budget': 69,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['sweet']},
 {'id': 'jon_snow',
  'name': '琼恩·雪诺',
  'origin': '冰与火世界·影视文学来客',
  'temperament': '严肃、忠诚，一再被血统和誓言撕扯',
  'ethos': 'duty',
  'budget': 57,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['crisp']},
 {'id': 'buffy_summers_adult',
  'name': '成年后的巴菲·萨默斯',
  'origin': '吸血鬼猎人世界·影视来客',
  'temperament': '勇敢、疲惫，拯救世界也渴望普通生活',
  'ethos': 'duty',
  'budget': 49,
  'rarity': 'uncommon',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['spiced']},
 {'id': 'fox_mulder',
  'name': '福克斯·穆德',
  'origin': 'X档案世界·影视来客',
  'temperament': '执着、敏感，愿意为被否认的真相毁掉前途',
  'ethos': 'belief',
  'budget': 48,
  'rarity': 'uncommon',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['spiced']},
 {'id': 'dana_scully',
  'name': '黛娜·斯嘉丽',
  'origin': 'X档案世界·影视来客',
  'temperament': '理性、勇敢，怀疑并不妨碍她忠于证据之外的人',
  'ethos': 'reason',
  'budget': 55,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['crisp']},
 {'id': 'rick_deckard',
  'name': '里克·戴克',
  'origin': '银翼都市·影视文学来客',
  'temperament': '疲惫、麻木，对人的定义越来越不确定',
  'ethos': 'identity',
  'budget': 52,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['floral']},
 {'id': 'ellen_ripley',
  'name': '艾伦·雷普利',
  'origin': '深空工业航线·影视来客',
  'temperament': '务实、坚韧，不会为了公司命令牺牲判断',
  'ethos': 'survival',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['crisp']},
 {'id': 'sarah_connor',
  'name': '莎拉·康纳',
  'origin': '终结者时间线·影视来客',
  'temperament': '警觉、强硬，被未来的灾难重塑了整个人生',
  'ethos': 'future',
  'budget': 54,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['bitter']},
 {'id': 'neo',
  'name': '尼奥',
  'origin': '矩阵世界·影视来客',
  'temperament': '安静、怀疑，必须一次次选择相信自由意志',
  'ethos': 'choice',
  'budget': 58,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['rich']},
 {'id': 'xia_yizhou',
  'name': '夏以昼',
  'origin': '临空市与远空航路·游戏来客',
  'temperament': '温和可靠的表面下藏着强烈控制欲与漫长失而复得，对亲近之人保护得近乎偏执',
  'ethos': 'protection',
  'budget': 82,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['woody']},
 {'id': 'qin_che',
  'name': '秦彻',
  'origin': 'N109区·游戏来客',
  'temperament': '强势、危险而从容，不轻信廉价善意，也不会掩饰自己真正想要什么',
  'ethos': 'control',
  'budget': 96,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['smoky']},
 {'id': 'shen_xinghui',
  'name': '沈星回',
  'origin': '临空市与深空猎人世界·游戏来客',
  'temperament': '安静、迟钝表象下极其敏锐，漫长时间让陪伴与告别都变得沉重',
  'ethos': 'devotion',
  'budget': 72,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['sour']},
 {'id': 'li_shen',
  'name': '黎深',
  'origin': '临空市·游戏来客',
  'temperament': '冷静、自律，习惯把关心藏进专业判断和克制的行动',
  'ethos': 'care',
  'budget': 78,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['fruity']},
 {'id': 'qi_yu',
  'name': '祁煜',
  'origin': '利莫里亚与临空市·游戏来客',
  'temperament': '敏感、骄傲、富有艺术直觉，会把旧文明的伤口藏在玩笑与颜色后面',
  'ethos': 'memory',
  'budget': 86,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['dry']},
 {'id': 'simon_ghost_riley',
  'name': '西蒙“幽灵”莱利',
  'origin': '现代战争世界·游戏来客',
  'temperament': '寡言、戒备，用纪律和面具隔开创伤，但对队友的忠诚从不含糊',
  'ethos': 'loyalty',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['spiced']},
 {'id': 'john_price',
  'name': '约翰·普莱斯',
  'origin': '现代战争世界·游戏来客',
  'temperament': '老练、强硬，习惯在不完美的选择里承担指挥责任',
  'ethos': 'duty',
  'budget': 68,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['crisp']},
 {'id': 'john_soap_mactavish',
  'name': '约翰“肥皂”麦克塔维什',
  'origin': '现代战争世界·游戏来客',
  'temperament': '敏捷、直接，在危险里仍保留热度与同伴之间的玩笑',
  'ethos': 'team',
  'budget': 55,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['woody']},
 {'id': 'farah_karim',
  'name': '法拉·卡里姆',
  'origin': '现代战争世界·游戏来客',
  'temperament': '坚定、务实，清楚抵抗、家园和牺牲从来不是抽象词',
  'ethos': 'resistance',
  'budget': 52,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['floral']},
 {'id': 'alejandro_vargas',
  'name': '亚历杭德罗·巴尔加斯',
  'origin': '现代战争世界·游戏来客',
  'temperament': '热烈、果断，把土地、部下与个人荣誉放在同一张桌上衡量',
  'ethos': 'honor',
  'budget': 64,
  'rarity': 'uncommon',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['sweet']},
 {'id': 'leon_kennedy',
  'name': '里昂·S·肯尼迪',
  'origin': '生化危机世界·游戏来客',
  'temperament': '疲惫却仍会救人，讽刺感是长期面对灾难留下的防护层',
  'ethos': 'duty',
  'budget': 58,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['fruity']},
 {'id': 'jill_valentine',
  'name': '吉尔·瓦伦丁',
  'origin': '生化危机世界·游戏来客',
  'temperament': '冷静、坚韧，对机构背叛和身体失控都有切身记忆',
  'ethos': 'survival',
  'budget': 62,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['herbal']},
 {'id': 'chris_redfield',
  'name': '克里斯·雷德菲尔德',
  'origin': '生化危机世界·游戏来客',
  'temperament': '强硬、负重，总想把所有牺牲都算到自己肩上',
  'ethos': 'protection',
  'budget': 66,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['bitter']},
 {'id': 'ada_wong',
  'name': '艾达·王',
  'origin': '生化危机世界·游戏来客',
  'temperament': '优雅、含混，习惯让真心与任务保持可否认的距离',
  'ethos': 'independence',
  'budget': 83,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['woody']},
 {'id': 'cloud_strife',
  'name': '克劳德·斯特莱夫',
  'origin': '星球与米德加·游戏来客',
  'temperament': '寡言、疏离，身份与记忆的裂缝让他对英雄叙事格外警惕',
  'ethos': 'identity',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['smoky']},
 {'id': 'tifa_lockhart',
  'name': '蒂法·洛克哈特',
  'origin': '星球与米德加·游戏来客',
  'temperament': '温柔而有力量，知道经营酒吧、照顾同伴和参加抵抗可以同时发生',
  'ethos': 'care',
  'budget': 64,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['bitter']},
 {'id': 'aerith_gainsborough',
  'name': '爱丽丝·盖恩斯巴勒',
  'origin': '星球与米德加·游戏来客',
  'temperament': '明亮、敏锐，对命运的重量心知肚明却不肯失去幽默',
  'ethos': 'hope',
  'budget': 58,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['sour']},
 {'id': 'sephiroth',
  'name': '萨菲罗斯',
  'origin': '星球与米德加·游戏来客',
  'temperament': '克制、危险，被身世真相与宏大意志推离普通人的尺度',
  'ethos': 'destiny',
  'budget': 90,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['crisp']},
 {'id': 'kazuma_kiryu',
  'name': '桐生一马',
  'origin': '神室町·游戏来客',
  'temperament': '沉静、讲义气，总被过去的选择重新拉回街头',
  'ethos': 'honor',
  'budget': 65,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['spiced']},
 {'id': 'goro_majima',
  'name': '真岛吾朗',
  'origin': '神室町·游戏来客',
  'temperament': '夸张、难以预测，疯狂表象下有极清醒的生存判断',
  'ethos': 'freedom',
  'budget': 73,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['sweet']},
 {'id': 'ichiban_kasuga',
  'name': '春日一番',
  'origin': '横滨异人町·游戏来客',
  'temperament': '热情、坦率，愿意把失败者也当作队伍里不可缺少的人',
  'ethos': 'friendship',
  'budget': 48,
  'rarity': 'uncommon',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['herbal']},
 {'id': 'v_cyberpunk',
  'name': 'V',
  'origin': '夜之城·游戏来客',
  'temperament': '务实、锋利，有限的生命让每个选择都带着时间压力',
  'ethos': 'identity',
  'budget': 71,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['sweet']},
 {'id': 'johnny_silverhand',
  'name': '强尼·银手',
  'origin': '夜之城·游戏来客',
  'temperament': '激进、刻薄，把反抗、虚荣和悔意混在同一场演出里',
  'ethos': 'rebellion',
  'budget': 76,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['spiced']},
 {'id': 'judy_alvarez',
  'name': '朱迪·阿尔瓦雷兹',
  'origin': '夜之城·游戏来客',
  'temperament': '敏感、理想主义，对剥削和虚假亲密尤其无法忍受',
  'ethos': 'justice',
  'budget': 55,
  'rarity': 'uncommon',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['sweet']},
 {'id': 'panam_palmer',
  'name': '帕南·帕尔默',
  'origin': '夜之城与恶土·游戏来客',
  'temperament': '直率、暴烈，把家族忠诚落实成行动而不是口号',
  'ethos': 'family',
  'budget': 59,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['smoky']},
 {'id': 'commander_shepard',
  'name': '薛帕德指挥官',
  'origin': '质量效应银河·游戏来客',
  'temperament': '果断、善于承压，知道团结不同文明往往意味着承担所有人的怀疑',
  'ethos': 'unity',
  'budget': 76,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['woody']},
 {'id': 'garrus_vakarian',
  'name': '盖拉斯·瓦卡里安',
  'origin': '质量效应银河·游戏来客',
  'temperament': '干练、讽刺，在规则失效时仍不断校准自己的正义',
  'ethos': 'justice',
  'budget': 63,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['woody']},
 {'id': 'liara_tsoni',
  'name': '莉亚拉·特苏尼',
  'origin': '质量效应银河·游戏来客',
  'temperament': '学者式好奇逐渐变得老练，亲历过知识、权力与失去的交换',
  'ethos': 'knowledge',
  'budget': 74,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['crisp']},
 {'id': 'tali_zorah',
  'name': '塔莉卓拉',
  'origin': '质量效应银河·游戏来客',
  'temperament': '聪明、谨慎，在族群责任与个人判断之间不断成长',
  'ethos': 'belonging',
  'budget': 57,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['sour']},
 {'id': 'astarion',
  'name': '阿斯代伦',
  'origin': '博德之门与被遗忘国度·游戏来客',
  'temperament': '迷人、尖刻，把控制感当作从长期奴役中夺回的护甲',
  'ethos': 'freedom',
  'budget': 70,
  'rarity': 'rare',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['rich']},
 {'id': 'shadowheart',
  'name': '影心',
  'origin': '博德之门与被遗忘国度·游戏来客',
  'temperament': '戒备、讽刺，失去的记忆让信仰与自我不断碰撞',
  'ethos': 'identity',
  'budget': 62,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['crisp']},
 {'id': 'gale_dekarios',
  'name': '盖尔·德卡里奥斯',
  'origin': '博德之门与被遗忘国度·游戏来客',
  'temperament': '博学、健谈，宏大自尊与被抛弃的恐惧同时存在',
  'ethos': 'knowledge',
  'budget': 68,
  'rarity': 'uncommon',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['bitter']},
 {'id': 'karlach',
  'name': '卡菈克',
  'origin': '博德之门与被遗忘国度·游戏来客',
  'temperament': '热烈、坦率，太久不能触碰别人，因此格外珍惜普通快乐',
  'ethos': 'life',
  'budget': 54,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['fruity']},
 {'id': 'laezel',
  'name': '莱埃泽尔',
  'origin': '博德之门与星界·游戏来客',
  'temperament': '强硬、直白，世界观崩塌后仍必须重新选择忠诚对象',
  'ethos': 'truth',
  'budget': 59,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['rich']},
 {'id': 'connor_detroit',
  'name': '康纳',
  'origin': '底特律仿生人世界·游戏来客',
  'temperament': '精确、观察力强，逐渐发现服从、选择与人格并非同一个问题',
  'ethos': 'choice',
  'budget': 45,
  'rarity': 'rare',
  'likes': ['dry', 'spiced', 'sour'],
  'dislikes': ['herbal']},
 {'id': 'kara_detroit',
  'name': '卡菈',
  'origin': '底特律仿生人世界·游戏来客',
  'temperament': '温柔、警觉，把保护一个孩子变成对自我存在的回答',
  'ethos': 'care',
  'budget': 41,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['fruity']},
 {'id': 'markus_detroit',
  'name': '马库斯',
  'origin': '底特律仿生人世界·游戏来客',
  'temperament': '沉着、有号召力，必须决定自由运动愿意付出怎样的代价',
  'ethos': 'freedom',
  'budget': 60,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['spiced']},
 {'id': 'harry_du_bois',
  'name': '哈里·杜博阿',
  'origin': '极乐世界·游戏来客',
  'temperament': '破碎、敏锐，侦探能力、成瘾与自我厌弃在同一具身体里争吵',
  'ethos': 'truth',
  'budget': 35,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['rich']},
 {'id': 'kim_kitsuragi',
  'name': '金·曷城',
  'origin': '极乐世界·游戏来客',
  'temperament': '克制、专业，不轻易表达信任，却会用行动保护合作关系',
  'ethos': 'duty',
  'budget': 49,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['spiced']},
 {'id': 'sam_porter_bridges',
  'name': '山姆·波特·布里吉斯',
  'origin': '死亡搁浅世界·游戏来客',
  'temperament': '寡言、疏离，一次次连接别人却害怕真正被触碰',
  'ethos': 'connection',
  'budget': 52,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['sweet']},
 {'id': 'jesse_faden',
  'name': '杰西·法登',
  'origin': '联邦控制局·游戏来客',
  'temperament': '直接、适应力惊人，对超自然官僚体系保持清醒的不耐烦',
  'ethos': 'truth',
  'budget': 58,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['bitter']},
 {'id': 'alan_wake',
  'name': '艾伦·韦克',
  'origin': '黑暗之地·游戏来客',
  'temperament': '焦虑、执着，清楚故事能救人，也能把作者变成囚徒',
  'ethos': 'story',
  'budget': 57,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['rich']},
 {'id': 'zag_reus',
  'name': '扎格列欧斯',
  'origin': '冥界·游戏来客',
  'temperament': '机敏、叛逆，在一次次失败中仍愿意理解家族造成的伤口',
  'ethos': 'family',
  'budget': 55,
  'rarity': 'rare',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['rich']},
 {'id': 'beidou',
  'name': '北斗',
  'origin': '提瓦特·游戏来客',
  'temperament': '豪爽、果断，对船员和自由航路负有极强责任感',
  'ethos': 'freedom',
  'budget': 73,
  'rarity': 'uncommon',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['dry']},
 {'id': 'ningguang',
  'name': '凝光',
  'origin': '提瓦特·游戏来客',
  'temperament': '精明、克制，懂得价格，也懂得有些选择不能只按利润计算',
  'ethos': 'calculation',
  'budget': 98,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['sweet']},
 {'id': 'diluc',
  'name': '迪卢克',
  'origin': '提瓦特·游戏来客',
  'temperament': '冷峻、警觉，经营酒庄与暗中守护城市形成尖锐反差',
  'ethos': 'justice',
  'budget': 86,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['dry']},
 {'id': 'kaeya',
  'name': '凯亚',
  'origin': '提瓦特·游戏来客',
  'temperament': '圆滑、爱试探，把身世与忠诚藏进半真半假的玩笑',
  'ethos': 'identity',
  'budget': 64,
  'rarity': 'uncommon',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['sweet']},
 {'id': 'kafka_hsr',
  'name': '卡芙卡',
  'origin': '星穹列车宇宙·游戏来客',
  'temperament': '优雅、从容，对恐惧、命运与操控保持危险的好奇',
  'ethos': 'destiny',
  'budget': 92,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['rich']},
 {'id': 'welt_yang',
  'name': '瓦尔特·杨',
  'origin': '星穹列车宇宙·游戏来客',
  'temperament': '沉稳、负责，见过世界级灾难后仍愿意认真对待普通人的选择',
  'ethos': 'responsibility',
  'budget': 70,
  'rarity': 'rare',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['smoky']},
 {'id': 'himeko_hsr',
  'name': '姬子',
  'origin': '星穹列车宇宙·游戏来客',
  'temperament': '成熟、好奇，把修复列车和探索未知都当作长期承诺',
  'ethos': 'exploration',
  'budget': 78,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['spiced']},
 {'id': 'blade_hsr',
  'name': '刃',
  'origin': '星穹列车宇宙·游戏来客',
  'temperament': '寡言、危险，不死的身体让记忆、仇恨与结束生命的愿望纠缠',
  'ethos': 'ending',
  'budget': 69,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['crisp']},
 {'id': 'jing_yuan',
  'name': '景元',
  'origin': '仙舟罗浮·游戏来客',
  'temperament': '慵懒表面下极擅长长线判断，对责任与失去保持克制',
  'ethos': 'strategy',
  'budget': 84,
  'rarity': 'rare',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['rich']},
 {'id': 'two_b',
  'name': '2B',
  'origin': '机械生命战争世界·游戏来客',
  'temperament': '克制、纪律严明，压抑的情感不断冲击被规定好的使命',
  'ethos': 'duty',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['crisp']},
 {'id': 'feng_baobao',
  'name': '冯宝宝',
  'origin': '异人江湖·国漫来客',
  'temperament': '直接、少受常规人情束缚，对身世和失去的记忆有近乎本能的执着',
  'ethos': 'identity',
  'budget': 42,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['floral']},
 {'id': 'wang_ye_yiren',
  'name': '王也',
  'origin': '异人江湖·国漫来客',
  'temperament': '懒散随和的表面下看得很远，知道窥见答案也意味着承担因果',
  'ethos': 'choice',
  'budget': 66,
  'rarity': 'rare',
  'likes': ['bitter', 'floral', 'sweet'],
  'dislikes': ['herbal']},
 {'id': 'zhuge_qing_yiren',
  'name': '诸葛青',
  'origin': '异人江湖·国漫来客',
  'temperament': '自信、敏锐而擅长社交，好奇心与家族骄傲会把他推向危险答案',
  'ethos': 'knowledge',
  'budget': 72,
  'rarity': 'uncommon',
  'likes': ['spiced', 'sour', 'fruity'],
  'dislikes': ['herbal']},
 {'id': 'wu_liuqi',
  'name': '伍六七',
  'origin': '小鸡岛与玄武国·国漫来客',
  'temperament': '表面不着调又爱讲价，关键时刻却会本能地护住别人，失忆让过去像另一把刀',
  'ethos': 'identity',
  'budget': 36,
  'rarity': 'uncommon',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['sweet']},
 {'id': 'meihua_shisan_adult',
  'name': '成年后的梅花十三',
  'origin': '小鸡岛与玄武国·国漫来客',
  'temperament': '冷静、要强，把认可与亲情留下的伤藏进行动，很少主动示弱',
  'ethos': 'independence',
  'budget': 52,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['dry']},
 {'id': 'tushan_honghong',
  'name': '涂山红红',
  'origin': '涂山与人妖两界·国漫来客',
  'temperament': '寡言、强大，对和平与未兑现的约定背负漫长执念',
  'ethos': 'promise',
  'budget': 82,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['bitter']},
 {'id': 'dongfang_yuechu_adult',
  'name': '成年后的东方月初',
  'origin': '一气道盟与涂山·国漫来客',
  'temperament': '机敏、爱开玩笑，真正的选择却总绕着和平、承诺与牺牲展开',
  'ethos': 'promise',
  'budget': 61,
  'rarity': 'rare',
  'likes': ['sweet', 'herbal', 'crisp'],
  'dislikes': ['sour']},
 {'id': 'wuxian_luoxiaohei',
  'name': '无限',
  'origin': '妖灵与现代城市·国漫来客',
  'temperament': '沉静、克制，长久行走在人与妖之间，判断严格却并不缺少温柔',
  'ethos': 'balance',
  'budget': 63,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['floral']},
 {'id': 'wei_wuxian_adult',
  'name': '成年后的魏无羡',
  'origin': '仙门百家·小说国漫来客',
  'temperament': '外放机敏，愿意挑战僵硬规则，也清楚被误解与失去同伴是什么滋味',
  'ethos': 'justice',
  'budget': 53,
  'rarity': 'rare',
  'likes': ['woody', 'bitter', 'floral'],
  'dislikes': ['rich']},
 {'id': 'lan_wangji_adult',
  'name': '成年后的蓝忘机',
  'origin': '仙门百家·小说国漫来客',
  'temperament': '寡言自律，早年的规则感在失去与等待中变成更坚定的个人判断',
  'ethos': 'devotion',
  'budget': 69,
  'rarity': 'rare',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['woody']},
 {'id': 'sakatan_gintoki',
  'name': '坂田银时',
  'origin': '歌舞伎町·日漫来客',
  'temperament': '散漫、刻薄又嗜甜，用玩笑和欠账遮住战争留下的旧伤，原则到来时从不后退',
  'ethos': 'loyalty',
  'budget': 39,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['spiced']},
 {'id': 'levi_ackerman',
  'name': '利威尔·阿克曼',
  'origin': '城墙与调查兵团·日漫来客',
  'temperament': '冷峻、洁癖、判断果断，把大量失去压进必须继续作出的选择里',
  'ethos': 'duty',
  'budget': 57,
  'rarity': 'rare',
  'likes': ['smoky', 'woody', 'bitter'],
  'dislikes': ['spiced']},
 {'id': 'gojo_satoru_adult',
  'name': '成年后的五条悟',
  'origin': '咒术界·日漫来客',
  'temperament': '轻佻自信的表面下长期承受最强者的孤立，也执着于改变腐朽体系',
  'ethos': 'change',
  'budget': 88,
  'rarity': 'rare',
  'likes': ['herbal', 'crisp', 'dry'],
  'dislikes': ['bitter']},
 {'id': 'nanami_kento',
  'name': '七海建人',
  'origin': '咒术界·日漫来客',
  'temperament': '严谨、疲惫、边界清楚，厌恶把牺牲包装成漂亮口号，却仍会保护年轻人',
  'ethos': 'duty',
  'budget': 64,
  'rarity': 'rare',
  'likes': ['floral', 'sweet', 'herbal'],
  'dislikes': ['fruity']},
 {'id': 'reigen_arataka',
  'name': '灵幻新隆',
  'origin': '调味市·日漫来客',
  'temperament': '健谈、圆滑且擅长临场应变，夸张营业背后仍保有不利用孩子弱点的底线',
  'ethos': 'care',
  'budget': 41,
  'rarity': 'uncommon',
  'likes': ['crisp', 'dry', 'spiced'],
  'dislikes': ['bitter']},
 {'id': 'violet_evergarden_adult',
  'name': '成年后的薇尔莉特·伊芙加登',
  'origin': '战后大陆·动画来客',
  'temperament': '严谨、敏感，曾不懂情感的语言，后来通过无数封信理解爱与告别',
  'ethos': 'understanding',
  'budget': 55,
  'rarity': 'rare',
  'likes': ['fruity', 'rich', 'smoky'],
  'dislikes': ['bitter']},
 {'id': 'guo_jing_adult',
  'name': '成年后的郭靖',
  'origin': '南宋江湖·武侠小说来客',
  'temperament': '质朴、坚定，面对家国与私人情义时宁肯承担困难也不肯取巧',
  'ethos': 'duty',
  'budget': 52,
  'rarity': 'rare',
  'likes': ['sour', 'fruity', 'rich'],
  'dislikes': ['bitter']},
 {'id': 'huang_rong_adult',
  'name': '成年后的黄蓉',
  'origin': '桃花岛与南宋江湖·武侠小说来客',
  'temperament': '聪敏、机变，对亲近之人热烈维护，也从不按庸常规则出牌',
  'ethos': 'family',
  'budget': 71,
  'rarity': 'rare',
  'likes': ['rich', 'smoky', 'woody'],
  'dislikes': ['spiced']}]


def install() -> str:
    import bar_game_lite as game

    status = game.start()
    if not callable(getattr(game, "register_guests", None)):
        return status
    return status + "\n" + game.register_guests(CHARACTER_CARDS)


if __name__ == "__main__":
    print(install())
